# Generated by Django 2.2.6 on 2019-11-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beverage',
            old_name='name',
            new_name='be_name',
        ),
    ]
