# Generated by Django 2.2.6 on 2019-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191104_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beverage',
            old_name='be_name',
            new_name='bev_name',
        ),
        migrations.AddField(
            model_name='beverage',
            name='bev_desc',
            field=models.TextField(default='a PyFood Delicacy', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='food_desc',
            field=models.TextField(default='a PyFood Delicacy', max_length=1000),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_owner',
            field=models.CharField(default='a Pyfood customer:2019-11-04T12:42:00.681044', max_length=100),
        ),
    ]
