# Generated by Django 2.2.6 on 2019-11-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20191104_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_owner',
            field=models.CharField(default='a Pyfood customer:2019-11-04T12:49:31.381672', max_length=100),
        ),
    ]
