# Generated by Django 2.2.6 on 2019-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20191104_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_owner',
            field=models.CharField(default='a Pyfood customer:2019-11-04T13:31:58.482231', max_length=100),
        ),
    ]
