# Generated by Django 2.2.6 on 2019-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20191104_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_owner',
            field=models.CharField(default='a Pyfood customer:2019-11-04T13:32:08.389999', max_length=100),
        ),
    ]
